# Generated by Django 3.2.2 on 2021-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_category_categoryflower_flower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
