# Generated by Django 3.2.2 on 2021-05-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_flower_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryflower',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='categoryflower',
            name='flower_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryFlower',
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
    ]
