# Generated by Django 3.2.2 on 2021-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Старая цена'),
        ),
    ]
