# Generated by Django 3.2.2 on 2021-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('APPLE PAY', 'Apple Pay'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('PAYPAL', 'Paypal')], max_length=10, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(choices=[('ДОСТАВКА', 'Доставка'), ('САМОВЫВОЗ', 'Самовывоз')], max_length=9, verbose_name='Способ доставки')),
                ('gift', models.BooleanField(default=False, verbose_name='Подарок')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('comments', models.TextField(verbose_name='Коментарии')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_date',),
            },
        ),
    ]
