# Generated by Django 3.2.2 on 2021-05-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_good_old_price'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total', models.PositiveIntegerField(verbose_name='Итого')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower', to='flowers.flower', verbose_name='Цветок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
