# Generated by Django 3.2.2 on 2021-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(verbose_name='Комментарии'),
        ),
    ]
